[package]
name = "comrak"
version = "0.5.1"
authors = ["Levene <wong.levene@gmail.com>"]
description = "Slide Markdown parser and formatter"
documentation = "https://docs.rs/comrak"
homepage = "https://github.com/kivikakk/comrak"
repository = "https://github.com/kivikakk/comrak"
readme = "README.md"
keywords = ["markdown", "commonmark"]
license = "BSD-2-Clause"
categories = ["text-processing", "parsing", "command-line-utilities"]
exclude = ["/hooks/*", "/script/*", "/vendor/*", "/.travis.yml", "/Makefile", "/spec_out.txt"]

[profile.release]
lto = true
opt-level = 'z'

[[bin]]
name = "comrak"
required-features = ["clap"]
doc = false

[dependencies]
typed-arena = "1.4.1"
regex = "1.0.1"
lazy_static = "1.0.1"
entities = "1.0.1"
unicode_categories = "0.1.1"
clap = { version = "2.32.0", optional = true }
twoway = "0.2"
pest = "2"
pest_derive = "2"
shell-words = "1.0"
# wasm-bindgen = "0.2"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3.55"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
timebomb = "0.1.2"
propfuzz = "0.0.1"

[features]
default = ["clap"]

[target.'cfg(not(windows))'.dependencies]
xdg = "^2.1"


[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
